### PR TITLE
board/pluto: Add support for Android USB Tethering

### PR DESCRIPTION
**Pull request by r4d10n**
Signed-off-by: Rakesh Peter <rakesh@asnaviram.in>

### CODE REVIEW

**Comment by mhennerich** [comment]
Can you explain how did you test this? Did you enable any additional kernel drivers?

**Comment by r4d10n** [comment]
Our test setup for this is as follows: We have a battery controller board, which can power Pluto and also route power along with the D+ and D- pins on the Data connector of Pluto.  We have connected these Power + Data pins to a Female Type A connector mounted on the board.  The intention is to use the same port for connecting a WiFi dongle (as standalone WiFi SDR) or a normal Type A to Type C cable to Android phone (for USB tethering). Both use cases were tested to work fine. For enabling DHCP on usb1 for assigning IP to Pluto from Android, the above commit needs to be in-place.

Additional kernel drivers had to be enabled for RNDIS and CDC Ether.  Please note that this is mostly meant for supporting earlier Android phones without Ethernet tethering / ECM.

**Comment by mhennerich** [comment]
Hmm - the pluto firmware supports RNDIS, NCM, or ECM since a while now. 
https://wiki.analog.com/university/tools/pluto/users/customizing?s[]=ncm#changing_the_usb_ethernet_compatibility_mode
For none of those I have never seen usb1 to be created.
So what exactly is usb1 in your case?

**Review by mhennerich — APPROVED** [review]
I don't see how this can negatively affect things.
So let's merge this.

**Comment by mhennerich** [comment]
Thanks this makes sense to me now.

**Pull request merged**
