### PR TITLE
Merge tag '2022.02.3' into HEAD

### PR DESCRIPTION
**Pull request by catkira**
just for fun, so that we can compare our merge results

### CODE REVIEW

**Comment by catkira** [comment]
it seems like there is no diff visible here, I will try to run a diff locally...

**Comment by catkira** [comment]
The first diff that shows up is this
```diff
diff --git a/Config.in.legacy b/Config.in.legacy
index a832ddf246..6724865232 100644
--- a/Config.in.legacy
+++ b/Config.in.legacy
@@ -835,53 +835,6 @@ config BR2_PACKAGE_KODI_SCREENSAVER_CRYSTALMORPH

 comment "Legacy options removed in 2021.02"

-config BR2_OPENJDK_VERSION_LTS
-       bool "OpenJDK LTS version was renamed to OpenJDK 11"
-       select BR2_LEGACY
-       select BR2_PACKAGE_OPENJDK_VERSION_11
-       help
-         The LTS version option was renamed to OpenJDK 11 to make it
-         clear what LTS version is.
-
-config BR2_OPENJDK_VERSION_LATEST
-       bool "OpenJDK latest version (16.x) was removed"
-       select BR2_LEGACY
-       select BR2_PACKAGE_OPENJDK_VERSION_17
-       help
-         OpenJDK 16.x is no longer mainted, so the option has been
-         removed. Use OpenJDK 17.x instead.
```

**Comment by nunojsa** [comment]
> I think the problem is that buildroot clones the whole repo, zips it and then calculates the hash value. Small difference like file meta information, different tar versions and things like that can cause a mismatch. I think using a hash value on a zipped git repo is not very reliable.

I have to say that this would be an issue for a lot more packages that are in buildroot and I guess a lot more complains would happen. So, I have the feeling this might be related to a more subtle issue...

**Comment by nunojsa** [comment]
> It would be nice to have a script that checks for every file if the file has any adi changes in its history, if not it should just directly take the upstream version when doing a merge. Files that have ADI changes should be normally merged and conflicts resolved by hand.

Honestly, I don't think it's worth the trouble. The only package that (most of the time) conflicts is libiio and we __should__ know how to resolve those conflicts :)

**Comment by catkira** [comment]
we solved the hash problem [here](https://github.com/analogdevicesinc/buildroot/issues/65)

**Pull request closed without merging**
