### PR TITLE
Modified zynq_sidekiqz2_defconfig with hardfp changes from zynq_pluto_defconfig

### PR DESCRIPTION
**Pull request by epiq-alex**
The change applies the contents of [this commit](https://github.com/analogdevicesinc/buildroot/commit/fea212afc7dc0ee530762a1921d9ae8180778ffa) to configs/zynq_sidekiqz2_defconfig, which appears to resolve an issue building plutosdr-fw.git, with `make TARGET=sidekiqz2`.

### CODE REVIEW

**Comment by epiq-alex** [comment]
@mhennerich Done!

**Comment by mhennerich** [comment]
merged

**Comment by epiq-alex** [comment]
Thanks! Would it be possible to update master on [plutosdr-fw](https://github.com/analogdevicesinc/plutosdr-fw) to reference the new commit?

**Comment by mhennerich** [comment]
done

**Pull request merged**
