### PR TITLE
sidekiqz2: use Pluto's msd data 

### PR DESCRIPTION
**Pull request by commodo**
After a bit of internal discussion it was decided to go ahead with just symlinking the `msd` for Pluto into SidekiqZ2.

If this changes later on, it can be re-adapted.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>

### CODE REVIEW

**Comment by commodo** [comment]
Changelog v1 -> v2:
* add back LICENSE.html file ; was removed in first version

**Comment by commodo** [comment]
Will merge this later today if no objections.

**Comment by commodo** [comment]
ok
sorry for the rush :)

will revert the patch

**Comment by rgetz** [comment]
thanks.

**Pull request merged**
