### PR TITLE
configs: fix kernel version for vivado 2019.1

### PR DESCRIPTION
**Pull request by commodo**
The toolchain reports 4.14 kernel version for headers. Though it's weird
because the kernel tag for 2019.1 has version 4.19.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>

### CODE REVIEW

**Comment by tfcollins** [comment]
Where does the toolchain pull the kernel version from?

-Travis

**Comment by mhennerich** [comment]
dave@HAL9000:/opt/Xilinx/SDK/2019.1/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc/usr/include/linux$ cat version.h 
#define LINUX_VERSION_CODE 265728
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

**Comment by tfcollins** [comment]
Strange

-Travis

**Comment by tfcollins** [comment]
Is that a Xilinx bug?

-Travis

**Comment by mhennerich** [comment]
I've seen this many times before. I don't think it's a bug.

**Comment by commodo** [comment]
if it is a xilinx bug, it's more of a confusion somewhere;
not sure if on our side, or on their git-tags on their Linux repo, or on their release somewhere;

but it's @mhennerich is saying; Vivado 2019.1 comes with 4.14 Linux headers;

**Comment by rgetz** [comment]
To be pedantic - there is the kernel, and the kernel that the toolchain is built against (the kernel headers in your toolchain). They don't need to be the same (should be, as long as you upgrade kernel headers the same as your kernel).

For example, on my desktop:
rgetz@brain:~$ cat /usr/include/linux/version.h
#define LINUX_VERSION_CODE 267126

that (267126) turns into: 4.19.118; my kernel is actually 4.19.0-8 (debian).

When we build a kernel - should we just replace the userspace kernel headers?

from the buildroot manual:
```
Since this interface is backward compatible, the version of the Linux kernel headers used to 
build your toolchain do not need to match exactly the version of the Linux kernel you intend
to run on your embedded system. They only need to have a version equal or older to the 
version of the Linux kernel you intend to run. If you use kernel headers that are more
recent than the Linux kernel you run on your embedded system, then the C library might 
be using interfaces that are not provided by your Linux kernel.
```

So if Buildroot looks at the kernel - that's wrong. It should be looking at the toolchain (unless it's using the `Internal toolchain backend`, which we are not).

Do I have that right?

**Comment by mhennerich** [comment]
In our setup, Buildroot  looks at the headers from the toolchain. So they are 4.14 and our kernel is 4.19, so everything should be ok.

**Pull request merged**
