### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by catkira**

### CODE REVIEW

**Comment by catkira** [comment]
@nunojsa should I also put a commit into this PR that deletes the hash files for ad936x and libiio? I think I wont be the only person that runs into the hash mismatch problem, but I also wonder why nobody else had the problem before me. Maybe because only 2-3 people build buildroot for themselves.

**Comment by nunojsa** [comment]
Well, I'm not sure about the hash files. They are in upstream buildroot so if it's an issue, it might have to do with something we're doing ourselves. Not sure...

**Comment by catkira** [comment]
yes they are in upstream but probably only used by this ADI fork. Does the hash work for you?

**Comment by catkira** [comment]
I also added a commit that makes zynq_pluto_defconfig compatible with Vitis 2022.1, however that also makes it incompatible with SDK 2019.1. What is the best way to handle this?

**Comment by catkira** [comment]
I have added a patch file that contains the necessary modifications to the Vitis 2022.1 installation. It would be nice if somebody can review the whole PR.

**Comment by catkira** [comment]
the zstd is needed for the latest libiio

**Comment by Johnsel** [comment]
@catkira your repo is private or deleted so I made a fork of this repo and applied your patches so other people can apply it more easily.

https://github.com/Johnsel/buildroot/tree/master-next

Do read the notes on how to patch your Vitis 2022.1 install.

**Comment by catkira** [comment]
keep in mind that this is all experimental and only for developers ^^

**Pull request closed without merging**
